insert into Person (Id, Name, Email, GenderId)
values (16, 'Supermees', 's@s.com', 2)
insert into Person (Id, Name, Email, GenderId)
values (15, 'Wonderwoman', 'w@w.com', 1)
insert into Person (Id, Name, Email, GenderId)
values (14, 'Batman', 'b@b.com', 2)
insert into Person (Id, Name, Email, GenderId)
values (13, 'Aquaman', 'a@a.com', 2)
insert into Person (Id, Name, Email, GenderId)
values (12, 'Catwoman', 'c@c.com', 1)
insert into Person (Id, Name, Email, GenderId)
values (11, 'Antman', 'ant"ant.com', 2)
insert into Person (Id, Name, Email, GenderId)
values (9, 'Spiderman', 'spider@spiderman.com', 2)